//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34011
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandyUtilConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandyUtilConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ｎｏ.,艦種,品名,税込価格,本体価格,メーカー
        ///103,戦艦,山城　やましろ,1785,&quot;1,700&quot;,Ａ
        ///104,戦艦,扶桑　ふそう,1785,&quot;1,700&quot;,Ａ
        ///109,戦艦,金剛　こんごう,2625,&quot;2,500&quot;,Ｈ
        ///110,戦艦,比叡　ひえい,2625,&quot;2,500&quot;,Ｈ
        ///111,戦艦,榛名　はるな,2625,&quot;2,500&quot;,Ｈ
        ///112,戦艦,霧島　きりしま,2625,&quot;2,500&quot;,Ｈ
        ///113,戦艦,大和　やまと,2520,&quot;2,400&quot;,Ｔ
        ///114,戦艦,武蔵　むさし,2520,&quot;2,400&quot;,Ｔ
        ///115,戦艦,長門　ながと,2520,&quot;2,400&quot;,Ａ
        ///116,戦艦,陸奥　むつ,2520,&quot;2,400&quot;,Ａ
        ///117,戦艦,伊勢　いせ,3360,&quot;3,200&quot;,Ｈ
        ///118,戦艦,日向　ひゅうが,3360,&quot;3,200&quot;,Ｈ
        ///119,航空戦艦,伊勢　いせ,3360,&quot;3,200&quot;,Ｈ
        ///120,航空戦艦,日向　ひゅうが,3360,&quot;3,200&quot;,Ｈ
        ///201,航空母艦,赤城　あかぎ,2310,&quot;2,200&quot;,Ｈ
        ///202,航空母艦,加賀　かが,2310,&quot;2,200&quot;, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelShips {
            get {
                return ResourceManager.GetString("ModelShips", resourceCulture);
            }
        }
    }
}
